### ISSUE TITLE
auto-formatting

### ISSUE THREAD

**Issue by xiii111** [Team-OW/NumberBullet2#129]
---
* keyword: git hooks precommit dotnet-format

**Comment by takesi0627** [comment]
* git precommit sample: https://yoshinorin.net/2018/01/07/git-pre-commit-code-format/

* dotnet-formater https://qiita.com/skitoy4321/items/f88fe188bc0f85351f3c

**Comment by xiii111** [comment]
自動クローズされてなかったので．
#132

**Comment by xiii111** [comment]
自動クローズされてなかったので．
#132
