### ISSUE TITLE
ステージ作成を簡略化する仕組みを作る

### ISSUE THREAD

**Issue by xiii111** [Team-OW/NumberBullet2#150]
現状，全てコードで引数を与えないと，ステージを作成できない．
これらを解決するための仕組みを作る

**Comment by takesi0627** [comment]
使用イメージ

![IMG_3D963B7EF944-1](https://user-images.githubusercontent.com/17778395/62833254-b2985000-bc76-11e9-94fe-ae880e62940a.jpeg)
