### ISSUE TITLE
主要な対象デバイスを選択する。

### ISSUE THREAD

**Issue by takasusuke** [Team-OW/NumberBullet2#216]
デバイスごとに必要な画像サイズを調べてまとめる。

**Comment by takasusuke** [comment]
### 対象とするデバイスについて
デバイスサイズは多様(特にAndroid)ですが、画像サイズを指定する場合、iPhoneならばpx、Androidならばdpという単位で指定するので、この単位でデバイスを指定しました。
2019年のシェア率に基づき、以下の6種類を指定しました。
- iPhone (6 / 6s / 7 / 8) : 375 x 667 (pt)
- iPhone (6 Plus / 6s Plus / 7 Plus 8 Plus) : 414 x 736 (pt)
- iPhone X : 375 x 812 (pt)
- iPhone XR : 414 x 896 (pt)
- iPad :  対象としない
- Android S(iPhone (5 / 5s / 5c SE)と同じ)  : 320 x 568 (dp)
- Android M : 360 x 640 (dp)
- Andorid  タブレット : 対象としない

iPhoneは6以降(実質5以降)、AndroidはiPhone XRよりシェア率の高い２種類を選びました。

### その他
- scrapbox (https://scrapbox.io/NumberBullet2/デザイン) にも同様の記述があります
- Unity 2019.3以降の新機能「Device Simulator」がどんなものか気になる。正式リリースされたら試してみたい。

### 参考URL
- https://www.webtech.co.jp/blog/optpix_labs/smartphone/8961/
- https://webseeya.com/smartphone-display-share/

**Comment by takasusuke** [comment]
タブレットのような大きいデバイスで遊ぶことを自分は想定していないので、対象としない（けど、縦横比の最も近いデバイスの比で表示するとは思う）としましたが、そこら辺の意見が聞きたいです。

**Comment by takasusuke** [comment]
結論
iPhone(pt)用とAndroid(dp)用の２種を用意する
画面レイアウトに応じて、配置を比率で決めたり、ポイントを指定する。
もし、縦横比に応じてデバイスごとにレイアウトを変更したくなった場合、
上記の6種類に対応する。

**Comment by xiii111** [comment]
閉じます！
