### ISSUE TITLE
ゲーム画面遷移時の不自然な見た目を直す

### ISSUE THREAD

**Issue by xiii111** [Team-OW/NumberBullet2#73]
ゲーム画面遷移時にカメラサイズが極端に狭くなる問題がある。
確認できたのでは、想定より横幅が削られる場合のみ。縦幅が削られるのは確認できていない。
あと、背景だけが表示される時間が異様に長い問題もここに関わっていると思う。

解決の指針として、多分だけど、処理し終えてちゃんと1フレーム待つとかすれば直ると思ってる。

**Comment by takasusuke** [comment]
画面の大きさが変わるのはエミュレータでだからかもしれない
とりあえず、ゲーム画面遷移時に、メニュー画面の背景が変わってそこにUIが表示される、みたいな今の状況を変える。
